
# ================================================================
# Settings
# ================================================================
[settings]
auto_install = false
minimum_release_age = "3d"
experimental = true


# ================================================================
# Tools
# ================================================================
[tools]
java = "openjdk-21"
yarn = "latest"
node = "24.2.0"
go = "latest"
watchexec = "latest"
uv = "latest"
biome = "latest"
pinact = "latest"
"github:k1LoW/mo" = "latest"
ghq = "latest"
delta = "latest"
